version: "3.4"
services:
  pico-1:
    image: pico:latest
    command:
      - server
      - --config.path
      - /etc/pico.yaml
      - --cluster.node-id-prefix
      - pico-1-
    hostname: pico-1
    volumes:
      - ./config/pico.yaml:/etc/pico.yaml

  pico-2:
    image: pico:latest
    command:
      - server
      - --config.path
      - /etc/pico.yaml
      - --cluster.node-id-prefix
      - pico-2-
    hostname: pico-2
    volumes:
      - ./config/pico.yaml:/etc/pico.yaml

  pico-3:
    image: pico:latest
    command:
      - server
      - --config.path
      - /etc/pico.yaml
      - --cluster.node-id-prefix
      - pico-3-
    hostname: pico-3
    volumes:
      - ./config/pico.yaml:/etc/pico.yaml

  load-balancer:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "pico-1"
      - "pico-2"
      - "pico-3"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - "pico-1"
      - "pico-2"
      - "pico-3"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - 3000:3000

networks:
  pico-network:
    driver: bridge
    name: pico-network
